version: "3.9"

services:
    api:
        build: ./api
        container_name:  api
        restart: always
        environment:
            - APP_NAME=FlaskApp
            - FLASK_ENV=development
        volumes:
            - ./api:/app
        ports:
            - "${THE_PORT:-5000}:5000"
