version: "3"

services:
    api:
        build: ./api
        container_name:  api
        restart: always
        environment:
            - APP_NAME=FlaskApp
            - FLASK_ENV=development
            - DB_HOSTNAME=database
            - DB_USERNAME=root
            - DB_PASSWORD=Pa$$w0rd123!
            - DB_NAME=cardio
        volumes:
            - ./api:/app
        ports:
            - "5000:5000"

    database:
        container_name: database
        image: mariadb/server:10.5
        restart: always
        environment:
            - MARIADB_ROOT_PASSWORD=Pa$$w0rd123!
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./db:/docker-entrypoint-initdb.d

volumes:
    db_data:
